server:
  port: 9000

logging:
  level:
    root: info
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG

management:
  endpoint:
    health:
      show-detail: always
      show-components: always

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
